/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sahmp
 */
public class company extends javax.swing.JFrame {
String usid="";
String pass="";
String ch="";
Connection cn=null;
Statement st=null;
ResultSet rs=null;
DefaultTableModel m=null;

String pri="";
double pr=0.0;
double total=0.0;

/**
     * Creates new form signup
     */
    public company() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        components = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbtab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        resistors = new javax.swing.JFrame();
        cb1 = new javax.swing.JComboBox<>();
        combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        db2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        sp1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        qt1 = new javax.swing.JTextField();
        mul2 = new javax.swing.JComboBox<>();
        bill = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        pricey = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        finuser = new javax.swing.JTextField();
        capacitors = new javax.swing.JFrame();
        dig1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        db3 = new javax.swing.JTable();
        sp2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        dig2 = new javax.swing.JComboBox<>();
        mul = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        qt2 = new javax.swing.JTextField();
        diodes = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tab3 = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        sp4 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        qt4 = new javax.swing.JTextField();
        inductors = new javax.swing.JFrame();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        dig3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        db4 = new javax.swing.JTable();
        dig4 = new javax.swing.JComboBox<>();
        sp3 = new javax.swing.JTextField();
        mul1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        qt3 = new javax.swing.JTextField();
        integrated = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        sp5 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        qt5 = new javax.swing.JTextField();
        transistors = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        sp6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        qt6 = new javax.swing.JTextField();
        information = new javax.swing.JFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        db5 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passfld = new javax.swing.JPasswordField();
        userid = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        components.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        components.setMinimumSize(new java.awt.Dimension(600, 500));
        components.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                componentsWindowOpened(evt);
            }
        });

        dbtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Component Id", "Device"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dbtab);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Components available in ElectroCompany");

        jLabel4.setText("Choose from table above and Enter exactly the same Id");

        jLabel23.setText("Some are not available currently");

        javax.swing.GroupLayout componentsLayout = new javax.swing.GroupLayout(components.getContentPane());
        components.getContentPane().setLayout(componentsLayout);
        componentsLayout.setHorizontalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentsLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentsLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(componentsLayout.createSequentialGroup()
                        .addComponent(textf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(103, 103, 103))))
            .addGroup(componentsLayout.createSequentialGroup()
                .addGroup(componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentsLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(componentsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(componentsLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        componentsLayout.setVerticalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentsLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(55, 55, 55))
        );

        resistors.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        resistors.setMinimumSize(new java.awt.Dimension(650, 450));
        resistors.setResizable(false);
        resistors.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                resistorsWindowOpened(evt);
            }
        });

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E24", "E48" }));

        jLabel5.setText("Select Resistor");

        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "u", "m", "", "K", "M", "G" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        db2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Wattage", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        db2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(db2);

        jLabel6.setText("E24 series has Tolerance 5% and E48 series has Tolerance 2%");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MFR", "CFR", "WIRE WOUND" }));

        jLabel8.setText("Choose wattage from table above");

        jButton4.setText("Check out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel22.setText("Quantity as an Integer");

        mul2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "10", "100", "1000", "10000", "100000" }));

        javax.swing.GroupLayout resistorsLayout = new javax.swing.GroupLayout(resistors.getContentPane());
        resistors.getContentPane().setLayout(resistorsLayout);
        resistorsLayout.setHorizontalGroup(
            resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resistorsLayout.createSequentialGroup()
                .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resistorsLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(49, 49, 49)
                        .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qt1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(resistorsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resistorsLayout.createSequentialGroup()
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(resistorsLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(124, 124, 124))
        );
        resistorsLayout.setVerticalGroup(
            resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resistorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(qt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(resistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        bill.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        bill.setMinimumSize(new java.awt.Dimension(600, 500));
        bill.setResizable(false);
        bill.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                billWindowOpened(evt);
            }
        });

        pricey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Component", "Specification", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pricey.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(pricey);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Cost");

        tot.setEditable(false);

        jButton5.setText("Choose");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel19.setText("Total bill for user:");

        finuser.setEditable(false);

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill.getContentPane());
        bill.getContentPane().setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billLayout.createSequentialGroup()
                        .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButton5)
                                .addGap(50, 50, 50)
                                .addComponent(jButton3))
                            .addGroup(billLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finuser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(billLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(finuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(billLayout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addGap(44, 44, 44))
        );

        capacitors.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        capacitors.setMinimumSize(new java.awt.Dimension(650, 450));
        capacitors.setPreferredSize(new java.awt.Dimension(650, 450));
        capacitors.setResizable(false);
        capacitors.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                capacitorsWindowOpened(evt);
            }
        });

        dig1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel9.setText("Select Capacitor");

        jButton6.setText("Proceed");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Check out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        db3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voltage", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        db3.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(db3);

        jLabel11.setText("Choose voltage from table above");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "p", "n", "u", "m", "", "K", "M", "G" }));

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ceramic", "Electrolytic" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.1pF", "0.25pF", "0.5pF", "1%", "2%", "3%", "5%", "10%", "20%" }));

        dig2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        mul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "10", "100", "1000", "10000", "100000" }));

        jLabel24.setText("Quantity as an Integer");

        javax.swing.GroupLayout capacitorsLayout = new javax.swing.GroupLayout(capacitors.getContentPane());
        capacitors.getContentPane().setLayout(capacitorsLayout);
        capacitorsLayout.setHorizontalGroup(
            capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capacitorsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(capacitorsLayout.createSequentialGroup()
                        .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, capacitorsLayout.createSequentialGroup()
                                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dig1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dig2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(capacitorsLayout.createSequentialGroup()
                        .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(capacitorsLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton6)))
                        .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(capacitorsLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capacitorsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(120, 120, 120))))))
        );
        capacitorsLayout.setVerticalGroup(
            capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capacitorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(qt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(capacitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        diodes.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        diodes.setMinimumSize(new java.awt.Dimension(650, 450));
        diodes.setPreferredSize(new java.awt.Dimension(650, 450));
        diodes.setResizable(false);
        diodes.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                diodesWindowOpened(evt);
            }
        });

        jLabel16.setText("Choose Id from table above");

        jButton17.setText("Proceed");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        tab3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company", "Current", "Voltage", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tab3);

        jButton18.setText("Check out");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Company");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel13.setText("Select Diode ");

        jLabel26.setText("Quantity as an Integer");

        javax.swing.GroupLayout diodesLayout = new javax.swing.GroupLayout(diodes.getContentPane());
        diodes.getContentPane().setLayout(diodesLayout);
        diodesLayout.setHorizontalGroup(
            diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diodesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(diodesLayout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jButton17)
                            .addGap(66, 66, 66)
                            .addComponent(jButton19)
                            .addGap(75, 75, 75)
                            .addComponent(jButton18))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diodesLayout.createSequentialGroup()
                            .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26))
                            .addGap(80, 80, 80)
                            .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sp4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qt4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        diodesLayout.setVerticalGroup(
            diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diodesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(qt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(diodesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton19)
                    .addComponent(jButton18))
                .addGap(27, 27, 27))
        );

        inductors.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        inductors.setMinimumSize(new java.awt.Dimension(650, 450));
        inductors.setPreferredSize(new java.awt.Dimension(650, 450));
        inductors.setResizable(false);
        inductors.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                inductorsWindowOpened(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "p", "n", "u", "m", "", "K", "M", "G" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "20%" }));

        dig3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel10.setText("Select Inductor");

        jButton8.setText("Proceed");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Check out");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        db4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        db4.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(db4);

        dig4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        mul1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "10", "100", "1000", "10000", "100000" }));

        jLabel12.setText("Choose Id from table above");

        jLabel25.setText("Quantity as an Integer");

        javax.swing.GroupLayout inductorsLayout = new javax.swing.GroupLayout(inductors.getContentPane());
        inductors.getContentPane().setLayout(inductorsLayout);
        inductorsLayout.setHorizontalGroup(
            inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inductorsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(inductorsLayout.createSequentialGroup()
                        .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(78, 78, 78)
                        .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sp3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(qt3)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inductorsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(dig3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dig4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(inductorsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(152, 152, 152))
        );
        inductorsLayout.setVerticalGroup(
            inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inductorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dig3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dig4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(qt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(inductorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        integrated.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        integrated.setMinimumSize(new java.awt.Dimension(650, 450));
        integrated.setResizable(false);
        integrated.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                integratedWindowOpened(evt);
            }
        });

        jLabel15.setText("Choose Id from table above");

        jButton14.setText("Proceed");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Check out");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Company");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company", "Pin", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tab2);

        jLabel17.setText("Select IC");

        jLabel27.setText("Quantity as an Integer");

        javax.swing.GroupLayout integratedLayout = new javax.swing.GroupLayout(integrated.getContentPane());
        integrated.getContentPane().setLayout(integratedLayout);
        integratedLayout.setHorizontalGroup(
            integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integratedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(integratedLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 328, Short.MAX_VALUE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(integratedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(89, 89, 89)
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(qt5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(integratedLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addGap(99, 99, 99)
                .addComponent(jButton15)
                .addGap(83, 83, 83))
        );
        integratedLayout.setVerticalGroup(
            integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integratedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(qt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(integratedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton16)
                    .addComponent(jButton15))
                .addContainerGap())
        );

        transistors.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        transistors.setMinimumSize(new java.awt.Dimension(650, 450));
        transistors.setPreferredSize(new java.awt.Dimension(650, 450));
        transistors.setResizable(false);
        transistors.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                transistorsWindowOpened(evt);
            }
        });

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company", "Voltage", "Current", "Beta", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tab1);

        jButton11.setText("Company");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel14.setText("Choose Id from table above");

        jButton12.setText("Proceed");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Check out");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel18.setText("Select Transistor");

        jLabel28.setText("Quantity as an Integer");

        javax.swing.GroupLayout transistorsLayout = new javax.swing.GroupLayout(transistors.getContentPane());
        transistors.getContentPane().setLayout(transistorsLayout);
        transistorsLayout.setHorizontalGroup(
            transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transistorsLayout.createSequentialGroup()
                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transistorsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transistorsLayout.createSequentialGroup()
                                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qt6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(transistorsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton12)
                        .addGap(132, 132, 132)
                        .addComponent(jButton11)
                        .addGap(115, 115, 115)
                        .addComponent(jButton13)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        transistorsLayout.setVerticalGroup(
            transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transistorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(qt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(transistorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11)
                    .addComponent(jButton13))
                .addGap(27, 27, 27))
        );

        information.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        information.setMinimumSize(new java.awt.Dimension(650, 400));
        information.setResizable(false);
        information.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                informationWindowOpened(evt);
            }
        });

        db5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company", "Headquaters"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(db5);

        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel21.setText("Prdoducts in ElectroCompany from Manufacturers");

        javax.swing.GroupLayout informationLayout = new javax.swing.GroupLayout(information.getContentPane());
        information.getContentPane().setLayout(informationLayout);
        informationLayout.setHorizontalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(278, 278, 278))
            .addGroup(informationLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informationLayout.setVerticalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("PASSWORD");

        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel1.setText("USERNAME");

        jLabel29.setText("Welcome to ElectroCompany");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(signup)
                .addGap(122, 122, 122)
                .addComponent(login)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passfld, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(userid)))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel29)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup)
                    .addComponent(login))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        try{
            usid=userid.getText();
            pass=new String(passfld.getPassword());
            String q1="";
            if(usid.isEmpty()==false)
            {
                q1="insert into user values('"+usid+"','"+pass+"');";
                st.executeUpdate(q1);
                JOptionPane.showMessageDialog(null,"Signup successful");
                userid.setText("");
                passfld.setText("");
            }
            else
                JOptionPane.showMessageDialog(null,"Enter correct details");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
            usid=userid.getText();
            pass=new String(passfld.getPassword());
            String q2="Select * from user where uid='"+usid+"' and pass='"+pass+"';";
            System.out.println(q2);
            rs=st.executeQuery(q2);
            if(rs.next())
            {
                components.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,"Login unsuccessful.\nSignup or check credentials.");
                userid.setText("");
                passfld.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 try{        
     Class.forName("com.mysql.jdbc.Driver");
     cn=DriverManager.getConnection("jdbc:mysql://localhost/esd","root","pass123");
     st=cn.createStatement();     
    }
 catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ch=textf.getText();
if(ch.equals("res"))
        {components.setVisible(false);
        resistors.setVisible(true);
        sp1.setText("");
qt1.setText("");
        }
else if(ch.equals("cap"))
        {components.setVisible(false);
        capacitors.setVisible(true);
        sp2.setText("");
qt2.setText("");
        }
else if(ch.equals("ic"))
        {components.setVisible(false);
        integrated.setVisible(true);
        sp3.setText("");
qt3.setText("");
        }
else if(ch.equals("dio"))
        {components.setVisible(false);
        diodes.setVisible(true);
        sp4.setText("");
qt4.setText("");
        }
else if(ch.equals("ind"))
        {components.setVisible(false);
        inductors.setVisible(true);
        sp5.setText("");
qt5.setText("");
        }
else if(ch.equals("tra"))
        {components.setVisible(false);
        transistors.setVisible(true);
        sp6.setText("");
qt6.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void componentsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_componentsWindowOpened
        DefaultTableModel model=(DefaultTableModel)dbtab.getModel();
        m=(DefaultTableModel)pricey.getModel();
        try{
            String query="select * from components;";
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("compid");
                        String b=rs.getString("device");
                        model.addRow(new Object[]{a,b});
                    }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_componentsWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
resistors.setVisible(false);
components.setVisible(true);
textf.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resistorsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_resistorsWindowOpened

        DefaultTableModel model1=(DefaultTableModel)db2.getModel();
        try{
            String query="select * from info;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                         String a=rs.getString("wattage");
                         double b=rs.getDouble("price");
                        model1.addRow(new Object[]{a,b});
                    }                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_resistorsWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
bill.setVisible(true);  
resistors.setVisible(false);

try{
pri="Select price from info where wattage="+sp1.getText()+";";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp1.getText()+"W",pr,qt1.getText()});
total=total+(Integer.valueOf(qt1.getText())*pr);
tot.setText("Rs. "+total);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
capacitors.setVisible(false);
components.setVisible(true);
textf.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
bill.setVisible(true);
capacitors.setVisible(false);
try{
pri="Select price from info1 where voltage="+sp2.getText()+";";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp2.getText()+"V",pr,qt2.getText()});
total=total+(Integer.valueOf(qt2.getText())*pr);
tot.setText("Rs. "+total);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void capacitorsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_capacitorsWindowOpened
DefaultTableModel model2=(DefaultTableModel)db3.getModel();
        try{
            String query="select * from info1;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("voltage");
                        double b=rs.getDouble("price");
                        model2.addRow(new Object[]{a,b});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }            // TODO add your handling code here:
    }//GEN-LAST:event_capacitorsWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
inductors.setVisible(false);
components.setVisible(true);
textf.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
inductors.setVisible(false);
bill.setVisible(true);
try{
pri="Select price from info3 where id='"+sp3.getText()+"';";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp3.getText(),pr,qt3.getText()});
total=total+(Integer.valueOf(qt3.getText())*pr);
tot.setText("Rs. "+total);
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void inductorsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_inductorsWindowOpened
        DefaultTableModel model3=(DefaultTableModel)db4.getModel();
        try{
            String query="select * from info3;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("id");
                        String b=rs.getString("type");
                        double c=rs.getDouble("price");
                        model3.addRow(new Object[]{a,b,c});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }            // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_inductorsWindowOpened

    private void informationWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_informationWindowOpened
        DefaultTableModel model4=(DefaultTableModel)db5.getModel();
        try{
            String query="select * from company;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("cid");
                        String b=rs.getString("cname");
                        String c=rs.getString("hdq");
                        model4.addRow(new Object[]{a,b,c});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }            // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_informationWindowOpened

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
transistors.setVisible(false);
components.setVisible(true);
textf.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
transistors.setVisible(false);
bill.setVisible(true);
try{
pri="Select price from transistors where id='"+sp6.getText()+"';";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp6.getText(),pr,qt6.getText()});
total=total+(Integer.valueOf(qt6.getText())*pr);
tot.setText("Rs. "+total);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
integrated.setVisible(false);
components.setVisible(true);
textf.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
integrated.setVisible(false);
bill.setVisible(true);  
try{
pri="Select price from integrated where id='"+sp5.getText()+"';";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp5.getText(),pr,qt5.getText()});
total=total+(Integer.valueOf(qt5.getText())*pr);
tot.setText("Rs. "+total);// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
diodes.setVisible(false);
components.setVisible(true);
textf.setText("");        // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
diodes.setVisible(false);
bill.setVisible(true);       
try{
pri="Select price from diodes where id='"+sp4.getText()+"';";
rs=st.executeQuery(pri);
rs.first();
pr=rs.getDouble("price");
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
}
m.addRow(new Object[]{ch,sp4.getText(),pr,qt4.getText()});
total=total+(Integer.valueOf(qt4.getText())*pr);
tot.setText("Rs. "+total);// TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
information.setVisible(true);
diodes.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
information.setVisible(true);
integrated.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
information.setVisible(true);
transistors.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed


if(ch.equals("ic"))
        {information.setVisible(false);
        integrated.setVisible(true);
        }
else if(ch.equals("dio"))
        {information.setVisible(false);
        diodes.setVisible(true);
        }
else if(ch.equals("tra"))
        {information.setVisible(false);
        transistors.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void transistorsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_transistorsWindowOpened
       DefaultTableModel mod1=(DefaultTableModel)tab1.getModel();
        try{
            String query="select * from transistors;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("id");
                        String b=rs.getString("com_id");
                        String d=rs.getString("vbe");
                        String e=rs.getString("ic");
                        String c=rs.getString("hfe");
                        String f=rs.getString("type");
                        double g=rs.getDouble("price");
                        mod1.addRow(new Object[]{a,b,d,e,c,f,g});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }            // TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_transistorsWindowOpened

    private void integratedWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_integratedWindowOpened
DefaultTableModel mod2=(DefaultTableModel)tab2.getModel();
        try{
            String query="select * from integrated;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("id");
                        String b=rs.getString("comp_id");
                       
                        String c=rs.getString("pin");
                        String f=rs.getString("type");
                        double g=rs.getDouble("price");
                        mod2.addRow(new Object[]{a,b,c,f,g});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }               // TODO add your handling code here:
    }//GEN-LAST:event_integratedWindowOpened

    private void diodesWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_diodesWindowOpened
DefaultTableModel mod3=(DefaultTableModel)tab3.getModel();
        try{
            String query="select * from diodes;";
            
            
                    rs=st.executeQuery(query);
                    while(rs.next()){
                        String a=rs.getString("id");
                        String b=rs.getString("co_id");
                        String d=rs.getString("current");
                        String e=rs.getString("voltage");
                        
                        String f=rs.getString("type");
                        double g=rs.getDouble("price");
                        mod3.addRow(new Object[]{a,b,d,e,f,g});
                    }
                    
                    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }               // TODO add your handling code here:
    }//GEN-LAST:event_diodesWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        components.setVisible(true);
        bill.setVisible(false);
        textf.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
            String q1="insert into bill(us,total) values('"+usid+"','"+total+"');";
                st.executeUpdate(q1);
                JOptionPane.showMessageDialog(null,"Thank you for shopping!");
        }    
                    
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
        }   
                System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void billWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_billWindowOpened
finuser.setText(usid);

// TODO add your handling code here:
    }//GEN-LAST:event_billWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame bill;
    private javax.swing.JFrame capacitors;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JFrame components;
    private javax.swing.JTable db2;
    private javax.swing.JTable db3;
    private javax.swing.JTable db4;
    private javax.swing.JTable db5;
    private javax.swing.JTable dbtab;
    private javax.swing.JComboBox<String> dig1;
    private javax.swing.JComboBox<String> dig2;
    private javax.swing.JComboBox<String> dig3;
    private javax.swing.JComboBox<String> dig4;
    private javax.swing.JFrame diodes;
    private javax.swing.JTextField finuser;
    private javax.swing.JFrame inductors;
    private javax.swing.JFrame information;
    private javax.swing.JFrame integrated;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton login;
    private javax.swing.JComboBox<String> mul;
    private javax.swing.JComboBox<String> mul1;
    private javax.swing.JComboBox<String> mul2;
    private javax.swing.JPasswordField passfld;
    private javax.swing.JTable pricey;
    private javax.swing.JTextField qt1;
    private javax.swing.JTextField qt2;
    private javax.swing.JTextField qt3;
    private javax.swing.JTextField qt4;
    private javax.swing.JTextField qt5;
    private javax.swing.JTextField qt6;
    private javax.swing.JFrame resistors;
    private javax.swing.JButton signup;
    private javax.swing.JTextField sp1;
    private javax.swing.JTextField sp2;
    private javax.swing.JTextField sp3;
    private javax.swing.JTextField sp4;
    private javax.swing.JTextField sp5;
    private javax.swing.JTextField sp6;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    private javax.swing.JTable tab3;
    private javax.swing.JTextField textf;
    private javax.swing.JTextField tot;
    private javax.swing.JFrame transistors;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
